<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gradle-project-properties>
  <!--DO NOT EDIT THIS FILE! - Used by the Gradle plugin of NetBeans.-->
  <target-platform-name>j2se</target-platform-name>
  <target-platform>1.7</target-platform>
  <source-level>1.7</source-level>
  <script-platform>
    <spec-name>j2se</spec-name>
    <spec-version>1.7</spec-version>
  </script-platform>
</gradle-project-properties>
